version: '{build}'

branches:
  only:
  - master

clone_depth: 5

matrix:
  fast_finish: true

install:
  - cinst winflexbison
  - win_flex --version
  - win_bison --version
  - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
  - 7z x .\WpdPack_4_1_2.zip -oc:\projects\libpcap\Win32
  - appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-0.1.zip
  - 7z x .\npcap-sdk-0.1.zip -oc:\projects\libpcap\Win32

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
      SDK: WpdPack
    - GENERATOR: "Visual Studio 12 2013 Win64"
      SDK: WpdPack
    - GENERATOR: "Visual Studio 12 2013"
      SDK: npcap-sdk-0.1
    - GENERATOR: "Visual Studio 12 2013 Win64"
      SDK: npcap-sdk-0.1

build_script:
  - type NUL >.devel
  - md build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH=c:\projects\libpcap\Win32\%SDK% -G%GENERATOR% ..
  - msbuild -nologo -p:Configuration=Release pcap.sln
